version: '3.9'

services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 82:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - mysql
      - php
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TIMEZONE: 'Asia/Tokyo'
    volumes:
      - ./data:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 9000:9000
      - 5173:5173
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379